Bat brain
ottoman-disc/the-woods pull request #20
Opened 2020-05-11 17:15 UTC by DamionSheppard

2020-05-11 20:18 UTC, mrhockeymonkey requested changes

2020-05-11 20:18 UTC, mrhockeymonkey commented on Assets/_Main/Scripts/AI/MotorAIController.cs
> +            void Move(Vector3 direction) => motor.Move(direction);
Methods in methods. this is a bad practise. Can't this just be "motor.Move()" ?

2020-05-11 20:18 UTC, mrhockeymonkey commented on Assets/_Main/Scripts/AI/MotorAIController.cs
> +        private Transform t;
could this be more descriptive. not sure what transform this will be

2020-05-11 20:18 UTC, mrhockeymonkey commented on Assets/_Main/Scripts/AI/MotorAIController.cs
> +            void Stop() => motor.Stop();
same

2020-05-11 20:18 UTC, mrhockeymonkey commented on Assets/_Main/Scripts/Combat/SimpleDamageable.cs
> +            SceneManager.LoadScene("Game DS");
you what now?

2020-05-11 20:18 UTC, mrhockeymonkey commented on Assets/_Main/Scripts/AI/MotorAIController.cs
> +            _targetPosition = this.transform.position;
is this required? looks like it is reassigned in Update(). is there some significance in targeting itself?

2020-05-12 08:07 UTC, DamionSheppard commented on Assets/_Main/Scripts/AI/MotorAIController.cs
> +            void Move(Vector3 direction) => motor.Move(direction);
Oh yeah, this was just a hangover from when they were public methods (repurposed MotorIntention). Will remove.

2020-05-12 08:13 UTC, DamionSheppard commented on Assets/_Main/Scripts/AI/MotorAIController.cs
> +        private Transform t;
Me a lazy boi, will sort

2020-05-12 08:27 UTC, DamionSheppard commented on Assets/_Main/Scripts/AI/MotorAIController.cs
> +            _targetPosition = this.transform.position;
It's only reassigned in Update() if we have a _targetTransform. Without this the bats all head to the origin. Probably a better implementation, but this is fine for now I think.

Will use the method instead and add comment to make clearer.

2020-05-12 08:28 UTC, DamionSheppard commented on Assets/_Main/Scripts/Combat/SimpleDamageable.cs
> +            SceneManager.LoadScene("Game DS");
This is temp behaviour. Quickest way to fake a dumb 'death' and reset the scene. Obviously no good for networking, but thats a different task. This is also obviously not how death should work ultimately. But, again, different task.

2020-05-12 19:37 UTC, mrhockeymonkey approved these changes

2020-05-12 20:40 UTC, merged